sudo: required
services: 
    - docker


before-install:
    - docker build -t NirmalBarik1/docker-react -f Dockerfile.dev .

script: 
    - docker run NirmalBarik1/docker-react npm run test -- --coverage

